/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#ffb77d",
        "surface-container-highest": "#353535",
        "on-secondary-container": "#b8b8b8",
        "primary-container": "#2792ff",
        "outline": "#8a919f",
        "surface-tint": "#a5c8ff",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "on-primary": "#00315f",
        "on-primary-container": "#002a53",
        "background": "#131313",
        "on-background": "#e5e2e1",
        "outline-variant": "#404753",
        "secondary": "#c7c6c6",
        "primary": "#a5c8ff",
        "on-error": "#690005",
        "on-secondary-fixed": "#1a1c1c",
        "secondary-fixed": "#e3e2e2",
        "on-tertiary": "#4d2600",
        "primary-fixed-dim": "#a5c8ff",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "surface-bright": "#393939",
        "on-primary-fixed": "#001c3a",
        "secondary-fixed-dim": "#c7c6c6",
        "surface": "#131313",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "surface-container-lowest": "#0e0e0e",
        "surface-container": "#20201f",
        "surface-variant": "#353535",
        "secondary-container": "#484949",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#da7700",
        "tertiary-fixed": "#ffdcc3",
        "primary-fixed": "#d4e3ff",
        "on-tertiary-fixed": "#2f1500",
        "on-secondary": "#2f3131",
        "inverse-primary": "#005faf",
        "tertiary-fixed-dim": "#ffb77d",
        "on-surface-variant": "#c0c7d6",
        // Light mode overrides
        "light-bg": "#f8f9fa",
        "light-surface": "#ffffff",
        "light-on-bg": "#1a1a1a",
        "light-primary": "#005faf",
        "light-on-surface-variant": "#4a5568",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        xs: "4px",
        base: "8px",
        "margin-mobile": "20px",
        gutter: "24px",
        md: "24px",
        "margin-desktop": "64px",
        xl: "80px",
        lg: "48px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }],
        display: ["64px", { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.8", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "mono-data": ["14px", { lineHeight: "1.5", letterSpacing: "0.02em", fontWeight: "400" }],
      },
      animation: {
        "spin-slow": "spin 20s linear infinite",
        "fade-up": "fadeUp 0.6s ease forwards",
        "ticker": "ticker 30s linear infinite",
      },
      keyframes: {
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        ticker: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
    },
  },
  plugins: [],
}
